version: '3'

name: mongo-sharding

services:
  # Сервер конфигурации
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - config-data:/data/db
    command: [ 
      "--configsvr", 
      "--replSet", "config_server", 
      "--bind_ip_all", 
      "--port", "27017" 
    ]

  # 1-й шард
  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27018:27018"
    networks:
      - app-network
    volumes:
      - shard1-data:/data/db
    command: [ 
      "--shardsvr", 
      "--replSet", "shard1_set", 
      "--bind_ip_all", 
      "--port", "27018" 
    ]

  # 2-й шард
  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27019:27019"
    networks:
      - app-network
    volumes:
      - shard2-data:/data/db
    command: [ 
      "--shardsvr", 
      "--replSet", "shard2_set", 
      "--bind_ip_all", 
      "--port", "27019" 
    ]

  # Роутер (mongos)
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      - app-network
    command: [ 
      "mongos", 
      "--configdb", "config_server/configSrv:27017", 
      "--bind_ip_all", 
      "--port", "27020" 
    ]
    depends_on:
      - configSrv

networks:
  app-network:
    driver: bridge

volumes:
  config-data:
  shard1-data:
  shard2-data:
